# Generated by Django 6.0.2 on 2026-03-01 20:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DurationField()),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(max_length=30)),
                ('instructions', models.TextField(max_length=1000)),
                ('serves', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('yields', models.CharField(blank=True, max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_fat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('saturated_fat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sugars', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge_manager.ingredient')),
                ('recipe_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge_manager.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('pk', models.CompositePrimaryKey('recipe_id', 'ingredient_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(blank=True, default=1)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge_manager.ingredient')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge_manager.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='UserIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fridge', models.BooleanField(default=True)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge_manager.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
