# Generated by Django 6.0.2 on 2026-03-02 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_manager', '0002_alter_useringredients_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('ME', 'Meat'), ('VG', 'Vegetable'), ('FR', 'Fruit'), ('CH', 'Cheese'), ('BE', 'Beans'), ('PO', 'Potato'), ('RI', 'Rice'), ('BR', 'Bread'), ('SA', 'Sauces'), ('CA', 'Candy'), ('PI', 'Pie'), ('DE', 'Dessert'), ('BF', 'Breakfast'), ('LU', 'Lunch/Snacks'), ('SW', 'Stew'), ('CD', 'Chowders'), ('SP', 'Spreads'), ('SD', 'Salad Dressings'), ('SC', 'Scones'), ('CO', 'Cookies'), ('ST', 'Stocks'), ('SM', 'Smoothies')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
