# Generated by Django 6.0.2 on 2026-03-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_review_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
